package damien.nodeworks.block.entity

import damien.nodeworks.network.Connectable
import damien.nodeworks.network.NodeConnectionHelper
import damien.nodeworks.registry.ModBlockEntities
import damien.nodeworks.script.cpu.BufferState
import damien.nodeworks.script.cpu.CpuOpExecutor
import damien.nodeworks.script.cpu.CpuRules
import damien.nodeworks.script.cpu.CraftPlan
import damien.nodeworks.script.cpu.CraftScheduler
import net.minecraft.core.BlockPos
import net.minecraft.core.HolderLookup
import net.minecraft.nbt.CompoundTag
import net.minecraft.nbt.Tag
import net.minecraft.network.protocol.Packet
import net.minecraft.network.protocol.game.ClientGamePacketListener
import net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket
import net.minecraft.server.level.ServerLevel
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.entity.BlockEntity
import net.minecraft.world.level.block.state.BlockState
import net.minecraft.world.level.storage.ValueInput
import net.minecraft.world.level.storage.ValueOutput
import damien.nodeworks.compat.getBlockPosList
import damien.nodeworks.compat.getIntOrNull
import damien.nodeworks.compat.getLongOrNull
import damien.nodeworks.compat.getStringOrNull
import damien.nodeworks.compat.putBlockPosList
import java.util.UUID

/**
 * Crafting Core, the brain of a multiblock Crafting CPU.
 *
 * Discovers CPU components (Buffer, Co-Processor, Substrate, Stabilizer) via free-form
 * adjacency BFS. Holds the buffer (both count and unique-types limits, Long-safe) and
 * drives craft execution.
 *
 * See docs/design/crafting-cpu.md for design rationale, [CpuRules] for tunables.
 */
class CraftingCoreBlockEntity(
    pos: BlockPos,
    state: BlockState
) : BlockEntity(ModBlockEntities.CRAFTING_CORE, pos, state), Connectable {

    private val connections = LinkedHashSet<BlockPos>()
    override var blockDestroyed: Boolean = false
    override var networkId: UUID? = null
        set(value) {
            val changed = field != value
            field = value
            // The CPU's emissive "active" block models are gated on the formed
            //  blockstate, and formed now requires a network membership, so when
            //  the network connection is wired/unwired, every cluster component
            //  needs its blockstate re-pushed. recalculateCapacity() walks the
            //  cluster and calls setBlock only where the desired state differs,
            //  so this is cheap when nothing changed.
            if (changed && level != null && !level!!.isClientSide) {
                recalculateCapacity()
            }
        }

    // =====================================================================
    // Buffer (dual-axis: count + unique types, Long-safe item counts)
    // =====================================================================

    /**
     * The CPU's in-flight item buffer. Encapsulates both count and types limits,
     * handles Long arithmetic, and owns its own NBT format. See [BufferState].
     */
    val bufferState = BufferState()

    // =====================================================================
    // Scheduler, per-CPU operation scheduler
    // =====================================================================

    /** Executor that translates [Operation]s into real side effects on this CPU. */
    private val opExecutor: CpuOpExecutor = CpuOpExecutor(this)

    /** The scheduler that drives all in-flight crafts for this CPU.
     *  Phase 2 uses a single thread, Phase 3 adds one per Co-Processor. */
    val scheduler: CraftScheduler = CraftScheduler(threadCount = 1, executor = opExecutor)

    /** Number of Co-Processor blocks discovered in the last multiblock scan. */
    var coProcessorCount: Int = 0
        private set

    /** Heat generated by Buffer (tier-scaled) + Co-Processor blocks in the multiblock. */
    var heatGenerated: Int = 0
        private set

    /** Cooling provided by Stabilizer blocks in the multiblock. */
    var heatCooled: Int = 0
        private set

    /** Current throttle multiplier, heatPenalty × substrateBonus. Fed to [CpuRules.opCost]
     *  by the [damien.nodeworks.script.cpu.CpuOpExecutor] every op. Recalculated whenever
     *  the multiblock changes. Range ≈ [THROTTLE_FLOOR, COOLING_BONUS_CAP]. */
    var throttle: Float = 1.0f
        private set

    /** Tree node IDs (from [damien.nodeworks.script.CraftTreeBuilder.CraftTreeNode.nodeId])
     *  whose op is currently being worked on right now. Live view, recomputed from the
     *  scheduler/executor state every read. */
    val activeNodeIds: Set<Int>
        get() {
            val plan = scheduler.currentPlan ?: return emptySet()
            val active = opExecutor.activeProcessOpIds
            if (active.isEmpty()) return emptySet()
            val out = HashSet<Int>(active.size)
            for (op in plan.ops) if (op.id in active && op.outputNodeId >= 0) out += op.outputNodeId
            return out
        }

    /** Tree node IDs whose op has fully completed. */
    val completedNodeIds: Set<Int>
        get() {
            val plan = scheduler.currentPlan ?: return emptySet()
            val done = scheduler.completedOpIds
            if (done.isEmpty()) return emptySet()
            val out = HashSet<Int>(done.size)
            for (op in plan.ops) if (op.id in done && op.outputNodeId >= 0) out += op.outputNodeId
            return out
        }

    /**
     * Submit a planned craft to this CPU's scheduler. Runs immediately if a thread
     * is idle, otherwise queues. [onComplete] fires exactly once when the plan
     * reaches DONE (true) or FAILED (false). Safe to call from any server-side context.
     */
    fun submitCraft(plan: CraftPlan, currentTick: Long, onComplete: ((Boolean) -> Unit)? = null) {
        // Wipe ALL stale resume info, opIds are plan-scoped (planner starts at 0) and any
        // entry left over from a previous craft will collide with this plan's op IDs and
        // incorrectly trigger the resume path (which skips handler invocation).
        // The save/load resume flow does NOT go through here, it restores the same plan
        // it saved, with the matching opResumeInfo intact, via NBT.
        if (opResumeInfo.isNotEmpty()) {
            opResumeInfo.clear()
            setChanged()
        }
        onComplete?.let { opExecutor.registerCompletionListener(plan, it) }
        scheduler.submit(plan, currentTick)
        setCrafting(true, plan.rootItemId.substringAfter(':').replace('_', ' '))
        setOriginalCraft(plan.rootItemId, plan.rootCount)
    }

    /** Set on first tick so we run [recalculateCapacity] exactly once after BE load, the
     *  multiblock scan can only succeed once adjacent chunks are loaded and their BEs exist,
     *  which isn't guaranteed during [loadAdditional] but is by the time the ticker runs. */
    @Transient
    private var capacityInitialized: Boolean = false

    /** Per-tick entry point, called by the block's BlockEntityTicker. */
    fun serverTick(level: ServerLevel) {
        if (!capacityInitialized) {
            capacityInitialized = true
            recalculateCapacity()
        }
        scheduler.tick(level.gameTime)
    }

    /** Total items currently held (Long-safe for networks with billions of items). */
    val bufferUsed: Long get() = bufferState.count

    /** Count-axis capacity. */
    val bufferCapacity: Long get() = bufferState.countCapacity

    /** Number of unique item types currently held. */
    val bufferTypesUsed: Int get() = bufferState.types

    /** Unique-types capacity. */
    val bufferTypesCapacity: Int get() = bufferState.typesCapacity

    /** Whether a crafting job is currently running. */
    var isCrafting: Boolean = false
        private set

    /** The item currently being crafted (display name for GUI). */
    var currentCraftItem: String = ""
        private set

    /** The reason the last craft plan failed (empty if none or if the last craft succeeded).
     *  Surfaced in the CPU GUI so players can debug without tailing the server log. Cleared
     *  on the next successful plan completion or when a new plan is submitted. The setter
     *  sanitizes raw exception traces so the GUI shows a single, readable line instead of
     *  Lua tracebacks or Java exception class prefixes. */
    var lastFailureReason: String = ""
        set(value) {
            field = sanitizeFailureReason(value).take(256)
            setChanged()
            level?.sendBlockUpdated(worldPosition, blockState, blockState, Block.UPDATE_ALL)
        }

    private fun sanitizeFailureReason(raw: String): String {
        if (raw.isEmpty()) return raw
        // Belt-and-braces: most call sites already strip via LuaExecGate.stripLuaTraceback.
        val noTraceback = damien.nodeworks.script.LuaExecGate.stripLuaTraceback(raw) ?: raw
        // First non-blank line only, the GUI's single-line label can't render multi-line.
        val firstLine = noTraceback.lineSequence().firstOrNull { it.isNotBlank() } ?: noTraceback
        // Drop "java.lang.IndexOutOfBoundsException: " etc. so the player sees only the message.
        val prefix = Regex("""\b(?:java|kotlin|org\.luaj)\.[\w.$]+(?:Exception|Error)?:\s*""")
        return prefix.replace(firstLine, "").trim()
    }

    /** Incremented on each plan boundary (cancel, success, failure) so any still-active
     *  resume polls on the global ResumeScheduler become stale and route their next pulled
     *  items straight to network storage instead of the now-idle buffer. */
    var jobGeneration: Int = 0
        private set

    /** Bump [jobGeneration] to invalidate any in-flight resume polls for this CPU. */
    fun invalidateInFlightPolls() { jobGeneration++ }

    // =====================================================================
    // Pending processing job metadata (persisted for resume after restart)
    // =====================================================================

    /** The top-level item ID that was originally requested (e.g. "minecraft:iron_helmet"). */
    var originalCraftId: String = ""
        private set

    /** The top-level count originally requested. Long-safe for bulk crafts. */
    var originalCraftCount: Long = 0L
        private set

    /** Craft tree snapshot taken at craft start, reflects the original storage state. Not persisted. */
    @Transient
    var craftTreeSnapshot: damien.nodeworks.script.CraftTreeBuilder.CraftTreeNode? = null

    /** Expected outputs per operation: list of (itemId, count). Long-safe. */
    var pendingOutputs: List<Pair<String, Long>> = emptyList()
        private set

    /** Number of async processing operations still pending. */
    var pendingCount: Int = 0
        private set

    /** Block positions + faces that job:pull() should poll for outputs. */
    var pendingPullTargets: List<Pair<BlockPos, net.minecraft.core.Direction>> = emptyList()
        private set

    /** Whether resume has been scheduled this session (prevents duplicate resume). */
    @Transient
    var resumeScheduled: Boolean = false

    /** Set the top-level craft request for resume after restart. Called once per craft. */
    fun setOriginalCraft(itemId: String, count: Long) {
        if (originalCraftId.isEmpty()) {
            originalCraftId = itemId
            originalCraftCount = count
            setChanged()
        }
    }

    /**
     * Called when job:pull() registers an async poll. Captures the pull target
     * coordinates and increments the pending count.
     */
    fun addPendingOp(outputs: List<Pair<String, Long>>, pullTargets: List<Pair<BlockPos, net.minecraft.core.Direction>>) {
        if (pendingOutputs.isEmpty()) pendingOutputs = outputs
        if (pendingPullTargets.isEmpty() && pullTargets.isNotEmpty()) pendingPullTargets = pullTargets
        pendingCount++
        setChanged()
    }

    /** Called when one async operation completes. Clears metadata when all are done. */
    fun completePendingOp() {
        pendingCount = maxOf(0, pendingCount - 1)
        if (pendingCount <= 0) clearPendingJob()
        else setChanged()
    }

    /** Per-op resume state, captured when a Process op's handler registers a pull, used
     *  on world reload to restart polling without re-invoking the handler. The handler's
     *  side effects (items placed in machines) survive the reload as actual block state,
     *  we just need to keep watching for the outputs to arrive. */
    data class OpResumeInfo(
        val processingApiName: String,
        val outputs: List<Pair<String, Long>>,
        val pullTargets: List<Pair<BlockPos, net.minecraft.core.Direction>>
    )

    /** Keyed by Operation.id. Persisted across save/load. */
    val opResumeInfo: MutableMap<Int, OpResumeInfo> = mutableMapOf()

    /** Called by [damien.nodeworks.script.ProcessingJob] when a handler registers job:pull
     *  for the Process op identified by [opId].
     *
     *  Limitation: handlers that call `job:pull` more than once per invocation get only
     *  their LAST pull recorded for resume, overwrites are last-wins. Typical handlers
     *  call pull once and aren't affected. Multi-pull handlers that fail to resume cleanly
     *  fall through to the standard fail-and-flush path. */
    fun setOpResume(opId: Int, info: OpResumeInfo) {
        if (opId < 0) return
        opResumeInfo[opId] = info
        setChanged()
    }

    /** Called by [damien.nodeworks.script.ProcessingJob] when its pulls finish for [opId]. */
    fun clearOpResume(opId: Int) {
        if (opId < 0) return
        if (opResumeInfo.remove(opId) != null) setChanged()
    }

    /** Wipe all pending job metadata (but keep originalCraft, cleared by clearAllCraftState). */
    fun clearPendingJob() {
        if (pendingOutputs.isNotEmpty() || pendingCount > 0 || pendingPullTargets.isNotEmpty()) {
            pendingOutputs = emptyList()
            pendingCount = 0
            pendingPullTargets = emptyList()
            setChanged()
        }
    }

    /** Wipe everything including the original craft request. Called when the entire craft is done or cancelled. */
    fun clearAllCraftState() {
        originalCraftId = ""
        originalCraftCount = 0L
        craftTreeSnapshot = null
        clearPendingJob()
        // Op IDs are plan-scoped (planner starts at 0). Stale entries would collide with
        // the next plan's op IDs and incorrectly trigger the resume path.
        if (opResumeInfo.isNotEmpty()) {
            opResumeInfo.clear()
            setChanged()
        }
    }

    // =====================================================================
    // Buffer operations, all count parameters/returns are Long
    // =====================================================================

    /**
     * Insert [count] of [itemId] into the buffer.
     *
     * Returns true on success, false if either the count or types limit would be exceeded.
     * Failure is atomic: nothing is inserted if the check fails.
     */
    fun addToBuffer(itemId: String, count: Long): Boolean {
        if (!bufferState.insert(itemId, count)) return false
        setChanged()
        return true
    }

    /**
     * Remove up to [count] of [itemId] from the buffer.
     * Returns the amount actually removed (≤ count, 0 if nothing to remove).
     */
    fun removeFromBuffer(itemId: String, count: Long): Long {
        val removed = bufferState.extract(itemId, count)
        if (removed > 0) setChanged()
        return removed
    }

    fun getBufferCount(itemId: String): Long = bufferState.get(itemId)

    fun getBufferContents(): Map<String, Long> = bufferState.contents()

    fun clearBuffer(): Map<String, Long> {
        val contents = bufferState.clear()
        if (contents.isNotEmpty()) setChanged()
        return contents
    }

    /** Returns true if [count] [itemId] can be accepted right now (doesn't modify state). */
    fun canAccept(itemId: String, count: Long): Boolean = bufferState.canAccept(itemId, count)

    fun setCrafting(crafting: Boolean, itemName: String = "") {
        isCrafting = crafting
        currentCraftItem = if (crafting) itemName else ""
        markDirtyAndSync()
    }

    /** Cancel the current job: abort scheduler threads, buffer contents return to network
     *  storage via the executor's standard onPlanFailed flush. */
    fun cancelJob() {
        if (level !is net.minecraft.server.level.ServerLevel) return
        scheduler.cancelAll("Cancelled by player")
        jobGeneration++
        clearAllCraftState()
        setCrafting(false)
    }

    // =====================================================================
    // Multiblock detection (free-form adjacency BFS)
    // =====================================================================

    /** Whether the CPU has at least one Buffer block (required to be active). */
    var isFormed: Boolean = false
        private set

    /**
     * BFS through the adjacency graph starting from the Core. Discovers every
     * [CpuComponentBlockEntity] and accumulates per-type contributions.
     *
     * Capped by [CpuRules.COMPONENTS_PER_CPU_CAP] to bound work on chunk load.
     */
    fun recalculateCapacity() {
        var totalCount = CpuRules.CORE_BASE_COUNT
        var totalTypes = CpuRules.CORE_BASE_TYPES
        var bufferCount = 0
        var coProcessors = 0
        var heatGen = 0

        // Collect discovered component positions by type so we can do the adjacency pass
        // after the graph walk. Substrate's contribution is *positional*, we count faces
        // between Substrate blocks and heat-generating components (Buffer / Co-Processor).
        val heatGenPositions = HashSet<BlockPos>()
        // Heat value per heat-gen, so we can count which heat is "reached" by Stabilizers.
        val heatByPosition = HashMap<BlockPos, Int>()
        val substratePositions = HashSet<BlockPos>()
        // HashSet so the per-heat-gen loop can test face-neighbor membership in O(1).
        val stabilizerPositions = HashSet<BlockPos>()
        val coProcessorPositions = ArrayList<BlockPos>()
        val bufferPositions = ArrayList<BlockPos>()

        val visited = mutableSetOf(worldPosition)
        val queue = ArrayDeque<BlockPos>()
        queue.add(worldPosition)
        var discovered = 0

        while (queue.isNotEmpty() && discovered < CpuRules.COMPONENTS_PER_CPU_CAP) {
            val pos = queue.removeFirst()
            for (dir in net.minecraft.core.Direction.entries) {
                val neighbor = pos.relative(dir)
                if (neighbor in visited) continue
                visited.add(neighbor)
                val entity = level?.getBlockEntity(neighbor) ?: continue
                if (entity is CpuComponentBlockEntity) {
                    queue.add(neighbor)
                    discovered++
                    when (entity) {
                        is CraftingStorageBlockEntity -> {
                            totalCount += entity.storageCapacity
                            totalTypes += entity.storageTypes
                            bufferCount++
                            heatGen += entity.storageHeat
                            heatGenPositions.add(neighbor)
                            heatByPosition[neighbor] = entity.storageHeat
                            bufferPositions.add(neighbor)
                        }
                        is CoProcessorBlockEntity -> {
                            coProcessors++
                            heatGen += entity.heat
                            heatGenPositions.add(neighbor)
                            heatByPosition[neighbor] = entity.heat
                            coProcessorPositions.add(neighbor)
                        }
                        is StabilizerBlockEntity -> {
                            stabilizerPositions.add(neighbor)
                        }
                        is SubstrateBlockEntity -> {
                            totalTypes += CpuRules.SUBSTRATE_TYPE_CONTRIBUTION
                            substratePositions.add(neighbor)
                        }
                    }
                }
            }
        }

        // Substrate adjacency pass, count every face where a Substrate block touches a
        // Buffer or Co-Processor. Substrate-to-Substrate faces don't count, Substrate touching
        // the Core itself doesn't count (Core doesn't generate heat). This is what makes
        // placement a puzzle: packed layouts (Substrate sandwiched between components) yield
        // more adjacencies per block than chains along one axis.
        var substrateAdjacencies = 0
        for (sPos in substratePositions) {
            for (dir in net.minecraft.core.Direction.entries) {
                if (sPos.relative(dir) in heatGenPositions) substrateAdjacencies++
            }
        }

        // PER-HEAT-GEN LOCAL BALANCE, for each heat-generator, compute its own heat
        // (base + hotspot adjacency penalty) and its own cooling (Stabilizer faces
        // directly touching it × per-face rating). Every rule operates at block-adjacency
        // distance so the player can reason about each block individually.
        //
        // Substrate does NOT participate: it neither generates heat nor carries cooling.
        // Its only mechanical role is the throttle bonus computed separately.
        // Pass 1: for each Stabilizer, compute its total cooling output (base + cluster
        // bonus from adjacent stabilizers), then divide that output across its heat-gen
        // face-neighbors. The resulting per-face contribution is what each touched
        // heat-gen receives from this particular stabilizer face.
        val stabContributionPerFace = HashMap<BlockPos, Float>()
        for (pos in stabilizerPositions) {
            var stabNeighbors = 0
            var heatGenNeighbors = 0
            for (dir in net.minecraft.core.Direction.entries) {
                val n = pos.relative(dir)
                if (n in stabilizerPositions) stabNeighbors++
                else if (n in heatGenPositions) heatGenNeighbors++
            }
            if (heatGenNeighbors <= 0) continue  // stabilizer with no heat-gen contact does nothing
            val output = CpuRules.STABILIZER_BASE_COOLING + stabNeighbors * CpuRules.STABILIZER_CLUSTER_BONUS
            stabContributionPerFace[pos] = output / heatGenNeighbors
        }

        // Pass 2: for each heat-gen, sum cooling contributions from adjacent stabilizer
        // faces and compute base+hotspot heat. Per-block throttle math and overheat level
        // are derived from the local heat vs cool comparison, exactly as before.
        val overheatLevelByPosition = HashMap<BlockPos, Int>()
        var totalHeat = 0
        var totalCooledFloat = 0f
        for (pos in heatGenPositions) {
            val baseHeat = heatByPosition[pos] ?: 0
            var hotspotFaces = 0
            var cool = 0f
            for (dir in net.minecraft.core.Direction.entries) {
                val n = pos.relative(dir)
                if (n in heatGenPositions) hotspotFaces++
                else cool += stabContributionPerFace[n] ?: 0f
            }
            val heat = baseHeat + hotspotFaces * CpuRules.HOTSPOT_HEAT_PER_FACE
            totalHeat += heat
            totalCooledFloat += minOf(cool, heat.toFloat())  // excess cooling wasted, not bonused
            // Level 0 = safe, 1 = warm (<=1/3 uncovered), 2 = hot (<=2/3), 3 = critical.
            val deficit = heat.toFloat() - cool
            val level = when {
                deficit <= 0f -> 0
                heat <= 0 -> 0
                deficit * 3f <= heat -> 1
                deficit * 3f <= heat * 2f -> 2
                else -> 3
            }
            overheatLevelByPosition[pos] = level
        }
        val totalCooled = totalCooledFloat.toInt()

        // "Formed" now also requires an active network membership, disconnecting the
        //  Core from the laser network flips this false, which drives every cluster
        //  block to swap its emissive-on model for the plain one.
        isFormed = bufferCount > 0 && networkId != null
        coProcessorCount = coProcessors
        heatGenerated = totalHeat
        heatCooled = totalCooled
        // Throttle = heatPenalty × substrateBonus. No coolingBonus, only Substrate can
        // push throttle above 1.0×. Keeps the "what makes it faster" story crisp.
        throttle = CpuRules.heatPenalty(totalHeat, totalCooled) *
                   CpuRules.substrateBonus(substrateAdjacencies)

        scheduler.threadCount = 1 + coProcessors * CpuRules.THREADS_PER_COPROCESSOR

        if (isFormed) {
            bufferState.setCapacities(totalCount, totalTypes)
        } else {
            bufferState.setCapacities(0L, 0)
        }
        // Push formed + overheating flags out to each heat-gen component so emissive
        // variants reflect cooling status per block. Only issues setBlock when the
        // state actually changes.
        updateHeatGenBlockStates(
            coProcessorPositions, bufferPositions,
            isFormed, overheatLevelByPosition
        )

        markDirtyAndSync()
        updateBlockState()
    }

    private fun updateHeatGenBlockStates(
        coProcessorPositions: List<BlockPos>,
        bufferPositions: List<BlockPos>,
        formed: Boolean,
        overheatLevelByPosition: Map<BlockPos, Int>
    ) {
        val lvl = level ?: return
        val coFormed = damien.nodeworks.block.CoProcessorBlock.FORMED
        val coLevel = damien.nodeworks.block.CoProcessorBlock.OVERHEAT_LEVEL
        for (p in coProcessorPositions) {
            val s = lvl.getBlockState(p)
            if (s.block !is damien.nodeworks.block.CoProcessorBlock) continue
            // An unformed CPU has no meaningful overheat signal, pin level to 0.
            val wantLevel = if (formed) (overheatLevelByPosition[p] ?: 0) else 0
            var next = s
            if (next.getValue(coFormed) != formed) next = next.setValue(coFormed, formed)
            if (next.getValue(coLevel) != wantLevel) next = next.setValue(coLevel, wantLevel)
            if (next !== s) lvl.setBlock(p, next, Block.UPDATE_ALL)
        }
        val bufFormed = damien.nodeworks.block.CraftingStorageBlock.FORMED
        val bufLevel = damien.nodeworks.block.CraftingStorageBlock.OVERHEAT_LEVEL
        for (p in bufferPositions) {
            val s = lvl.getBlockState(p)
            if (s.block !is damien.nodeworks.block.CraftingStorageBlock) continue
            val wantLevel = if (formed) (overheatLevelByPosition[p] ?: 0) else 0
            var next = s
            if (next.getValue(bufFormed) != formed) next = next.setValue(bufFormed, formed)
            if (next.getValue(bufLevel) != wantLevel) next = next.setValue(bufLevel, wantLevel)
            if (next !== s) lvl.setBlock(p, next, Block.UPDATE_ALL)
        }
    }

    /**
     * Syncs the block entity's formed status to the block state,
     * which drives the model variant (emissive on/off) and triggers a chunk rebuild
     * so the block color provider re-evaluates the network color.
     */
    private fun updateBlockState() {
        val lvl = level ?: return
        val state = blockState
        if (state.block !is damien.nodeworks.block.CraftingCoreBlock) return
        val formedProp = damien.nodeworks.block.CraftingCoreBlock.FORMED
        if (state.getValue(formedProp) != isFormed) {
            lvl.setBlock(worldPosition, state.setValue(formedProp, isFormed), Block.UPDATE_ALL)
        }
    }

    // =====================================================================
    // Connectable
    // =====================================================================

    override fun getConnections(): Set<BlockPos> = connections

    override fun addConnection(pos: BlockPos): Boolean {
        if (!connections.add(pos)) return false
        markDirtyAndSync()
        return true
    }

    override fun removeConnection(pos: BlockPos): Boolean {
        if (!connections.remove(pos)) return false
        markDirtyAndSync()
        return true
    }

    override fun hasConnection(pos: BlockPos): Boolean = connections.contains(pos)

    // =====================================================================
    // Lifecycle
    // =====================================================================

    override fun setLevel(level: net.minecraft.world.level.Level) {
        super.setLevel(level)
        if (level is ServerLevel) {
            NodeConnectionHelper.trackNode(level, worldPosition)
            NodeConnectionHelper.queueRevalidation(level, worldPosition)
            // Defer recalc, neighbors may not be loaded yet.
            // Schedule resume of pending jobs
            // Legacy resume path, only fires when there's no per-op resume info AND no
            // persisted scheduler plan. Per-op resume (handled in CpuOpExecutor.executeProcess)
            // is the canonical recovery for new saves, the legacy path stays for compat with
            // pre-Phase-3 saves where Process state wasn't tracked per op.
            if (isCrafting && pendingCount > 0 && pendingPullTargets.isNotEmpty() &&
                !resumeScheduled &&
                opResumeInfo.isEmpty() && scheduler.currentPlan == null
            ) {
                resumeScheduled = true
                // Defer 2 seconds (40 ticks) to ensure chunk neighbors are loaded
                damien.nodeworks.script.ResumeScheduler.scheduler.addPendingJob(
                    damien.nodeworks.script.SchedulerImpl.PendingJob(
                        pollFn = pollFnResume@{
                            if (damien.nodeworks.script.ResumeScheduler.scheduler.currentTick < 40) return@pollFnResume false
                            resumePendingJobs()
                            true
                        },
                        timeoutAt = Long.MAX_VALUE,
                        label = "cpu-resume:$worldPosition"
                    )
                )
            }
        }
        damien.nodeworks.render.NodeConnectionRenderer.trackConnectable(level, worldPosition, true)
    }

    /**
     * Reconstruct processing job polls from persisted pull targets.
     * Called once after world load when the CPU has pending operations.
     */
    private fun resumePendingJobs() {
        val lvl = level as? ServerLevel ?: return
        if (pendingCount <= 0 || pendingPullTargets.isEmpty()) return

        val logger = org.slf4j.LoggerFactory.getLogger("nodeworks-resume")
        logger.info(
            "CPU at {}: resuming {} pending ops with {} pull targets",
            worldPosition, pendingCount, pendingPullTargets.size
        )

        // Build fresh storage getters from persisted coordinates
        val getters = pendingPullTargets.map { (pos, face) ->
            damien.nodeworks.script.CardHandle.StorageGetter {
                damien.nodeworks.platform.PlatformServices.storage.getItemStorage(lvl, pos, face)
            }
        }

        // Synthetic API info, only outputs matter for polling.
        // ProcessingApiInfo.outputs is (String, Int). We down-cast our Long pendingOutputs
        // for the synthetic API (the underlying processing pipeline will be refactored in
        // a later phase to handle Long end-to-end).
        val syntheticOutputs = pendingOutputs.map { it.first to it.second.coerceAtMost(Int.MAX_VALUE.toLong()).toInt() }
        val apiInfo = damien.nodeworks.block.entity.ProcessingStorageBlockEntity.ProcessingApiInfo(
            name = "resume",
            inputs = emptyList(),
            outputs = syntheticOutputs,
            timeout = 6000
        )

        for (i in 0 until pendingCount) {
            val pending = damien.nodeworks.script.CraftingHelper.PendingHandlerJob()
            pending.onCompleteCallback = {
                if (this.pendingCount <= 0) {
                    onPendingPullsComplete(lvl, logger)
                }
            }

            val job = damien.nodeworks.script.ProcessingJob(
                apiInfo, this, lvl,
                damien.nodeworks.script.ResumeScheduler.scheduler,
                pending
            )
            job.startPoll(getters)
        }
    }

    /**
     * Called when all persisted pull operations complete after a resume.
     * Re-invokes CraftingHelper.craft() with the original request so the
     * remaining craft steps (assembly, more sub-crafts) continue.
     */
    private fun onPendingPullsComplete(lvl: ServerLevel, logger: org.slf4j.Logger) {
        val craftId = originalCraftId
        val craftCount = originalCraftCount

        if (craftId.isEmpty()) {
            logger.info("CPU at {}: pulls complete but no original craft, flushing buffer", worldPosition)
            flushBufferAndRelease(lvl)
            return
        }

        logger.info("CPU at {}: pulls complete, re-invoking craft('{}', {})", worldPosition, craftId, craftCount)

        // Re-invoke craft with the original request, reusing this CPU.
        // CraftingHelper.craft signature still takes Int, caller-side cast is narrowed.
        // (Helper will be updated to Long in a later phase of the refactor.)
        val snap = damien.nodeworks.network.NetworkDiscovery.discoverNetwork(lvl, worldPosition)
        damien.nodeworks.script.CraftingHelper.currentPendingJob = null
        val clampedCount = craftCount.coerceAtMost(Int.MAX_VALUE.toLong()).toInt()
        val result = damien.nodeworks.script.CraftingHelper.craft(
            craftId, clampedCount, lvl, snap,
            cpuPos = worldPosition,
            callerScheduler = damien.nodeworks.script.ResumeScheduler.scheduler
        )
        val pending = damien.nodeworks.script.CraftingHelper.currentPendingJob
        damien.nodeworks.script.CraftingHelper.currentPendingJob = null

        if (result != null) {
            logger.info("CPU at {}: re-craft completed synchronously", worldPosition)
            flushBufferAndRelease(lvl)
        } else if (pending != null) {
            pending.onCompleteCallback = { _ ->
                flushBufferAndRelease(lvl)
                logger.info("CPU at {}: re-craft async completed", worldPosition)
            }
        } else {
            val reason = damien.nodeworks.script.CraftingHelper.lastFailReason
            logger.warn("CPU at {}: re-craft failed: {}", worldPosition, reason)
            flushBufferAndRelease(lvl)
        }
    }

    /** Flush all buffer contents to network storage, clear craft state, release CPU. */
    private fun flushBufferAndRelease(lvl: ServerLevel) {
        val snap = damien.nodeworks.network.NetworkDiscovery.discoverNetwork(lvl, worldPosition)
        val leftovers = clearBuffer()
        for ((itemId, count) in leftovers) {
            val id = net.minecraft.resources.Identifier.tryParse(itemId) ?: continue
            val item = net.minecraft.core.registries.BuiltInRegistries.ITEM.getValue(id) ?: continue
            var remaining = count
            while (remaining > 0L) {
                val batch = minOf(remaining, item.getDefaultMaxStackSize().toLong()).toInt()
                val stack = net.minecraft.world.item.ItemStack(item, batch)
                val inserted = damien.nodeworks.script.NetworkStorageHelper.insertItemStack(lvl, snap, stack, null)
                remaining -= inserted.toLong()
                if (inserted == 0) break
            }
        }
        clearAllCraftState()
        setCrafting(false)
    }

    override fun setRemoved() {
        damien.nodeworks.render.NodeConnectionRenderer.trackConnectable(level, worldPosition, false)
        val lvl = level
        if (lvl is ServerLevel) {
            NodeConnectionHelper.removeAllConnections(lvl, this)
            NodeConnectionHelper.untrackNode(lvl, worldPosition)
        }
        super.setRemoved()
    }

    private fun markDirtyAndSync() {
        setChanged()
        level?.sendBlockUpdated(worldPosition, blockState, blockState, Block.UPDATE_ALL)
    }

    // =====================================================================
    // Serialization
    // =====================================================================

    override fun saveAdditional(output: ValueOutput) {
        super.saveAdditional(output)
        output.putBlockPosList("connections", connections)
        output.putBoolean("isFormed", isFormed)
        output.putBoolean("isCrafting", isCrafting)
        output.putString("currentCraftItem", currentCraftItem)
        if (lastFailureReason.isNotEmpty()) output.putString("lastFailureReason", lastFailureReason)
        networkId?.let { output.putString("networkId", it.toString()) }

        // Buffer state, the BufferState helper still speaks the CompoundTag API internally
        // (streaming ValueOutput doesn't help here since the data is a small fixed blob),
        // so we round-trip via CompoundTag.CODEC as a store child.
        val bufferTag = CompoundTag()
        bufferState.saveToNBT(bufferTag)
        output.store("bufferState", CompoundTag.CODEC, bufferTag)

        // Scheduler state, same pattern.
        val schedulerTag = CompoundTag()
        scheduler.saveToNBT(schedulerTag)
        output.store("scheduler", CompoundTag.CODEC, schedulerTag)

        // Original craft request + pending job metadata (server-only, stripped in getUpdateTag).
        if (originalCraftId.isNotEmpty()) {
            output.putString("originalCraftId", originalCraftId)
            output.putLong("originalCraftCount", originalCraftCount)
        }
        if (pendingCount > 0) {
            output.putInt("pendingCount", pendingCount)
            val outsList = output.childrenList("pendingOutputs")
            for ((id, ct) in pendingOutputs) {
                val child = outsList.addChild()
                child.putString("id", id)
                child.putLong("ct", ct)
            }
            val targetsList = output.childrenList("pendingPullTargets")
            for ((pos, face) in pendingPullTargets) {
                val child = targetsList.addChild()
                child.putLong("p", pos.asLong())
                child.putInt("f", face.ordinal)
            }
        }

        // Per-op resume info, survives save/load so an in-progress smelt can pick up where
        // it left off without re-invoking the handler.
        if (opResumeInfo.isNotEmpty()) {
            val list = output.childrenList("opResumeInfo")
            for ((opId, info) in opResumeInfo) {
                val c = list.addChild()
                c.putInt("op", opId)
                c.putString("api", info.processingApiName)
                val outsList = c.childrenList("outputs")
                for ((id, ct) in info.outputs) {
                    val o = outsList.addChild()
                    o.putString("id", id)
                    o.putLong("ct", ct)
                }
                val tgtsList = c.childrenList("targets")
                for ((pos, face) in info.pullTargets) {
                    val t = tgtsList.addChild()
                    t.putLong("p", pos.asLong())
                    t.putInt("f", face.ordinal)
                }
            }
        }
    }

    override fun loadAdditional(input: ValueInput) {
        super.loadAdditional(input)
        connections.clear()
        connections.addAll(input.getBlockPosList("connections"))
        isFormed = input.getBooleanOr("isFormed", false)
        isCrafting = input.getBooleanOr("isCrafting", false)
        currentCraftItem = input.getStringOr("currentCraftItem", "")
        lastFailureReason = input.getStringOr("lastFailureReason", "")
        networkId = input.getStringOrNull("networkId")?.takeIf { it.isNotEmpty() }?.let {
            try { UUID.fromString(it) } catch (_: Exception) { null }
        }
        damien.nodeworks.network.NetworkSettingsRegistry.notifyConnectableChanged(networkId)

        // Load buffer, new format first, legacy "buffer" + "bufferCapacity" format as fallback
        // for pre-Phase-1 worlds. Both come through as CompoundTag sub-values via the codec.
        val bufferStateTag = input.read("bufferState", CompoundTag.CODEC).orElse(null)
        if (bufferStateTag != null) {
            bufferState.loadFromNBT(bufferStateTag)
        } else {
            val legacyBuffer = input.read("buffer", CompoundTag.CODEC).orElse(null)
            if (legacyBuffer != null) {
                bufferState.loadFromNBT(legacyBuffer)
                val legacyCap = input.getIntOrNull("bufferCapacity")
                if (legacyCap != null) {
                    bufferState.setCapacities(legacyCap.toLong(), CpuRules.CORE_BASE_TYPES)
                }
            }
        }

        // Scheduler state, optional for pre-Phase-2 saves.
        input.read("scheduler", CompoundTag.CODEC).ifPresent { scheduler.loadFromNBT(it) }

        // Load original craft request + pending job metadata
        originalCraftId = input.getStringOr("originalCraftId", "")
        // Long-safe with Int fallback, older saves used putInt for this.
        originalCraftCount = input.getLongOrNull("originalCraftCount")
            ?: input.getIntOrNull("originalCraftCount")?.toLong()
            ?: 0L
        pendingCount = input.getIntOr("pendingCount", 0)
        pendingOutputs = if (pendingCount > 0) {
            val list = input.childrenListOrEmpty("pendingOutputs")
            val out = ArrayList<Pair<String, Long>>()
            for (child in list) {
                val id = child.getStringOr("id", "")
                if (id.isEmpty()) continue
                val ct = child.getLongOr("ct", 0L)
                out += id to ct
            }
            out
        } else emptyList()
        pendingPullTargets = if (pendingCount > 0) {
            val list = input.childrenListOrEmpty("pendingPullTargets")
            val out = ArrayList<Pair<BlockPos, net.minecraft.core.Direction>>()
            for (child in list) {
                val p = child.getLongOr("p", 0L)
                val f = child.getIntOr("f", 0)
                val faces = net.minecraft.core.Direction.entries
                if (f !in faces.indices) continue
                out += BlockPos.of(p) to faces[f]
            }
            out
        } else emptyList()
        resumeScheduled = false

        // Per-op resume info, restore so executeProcess can poll without re-invoking handlers.
        opResumeInfo.clear()
        for (c in input.childrenListOrEmpty("opResumeInfo")) {
            val opId = c.getIntOr("op", -1)
            if (opId < 0) continue
            val api = c.getStringOr("api", "")
            val outputs = ArrayList<Pair<String, Long>>()
            for (o in c.childrenListOrEmpty("outputs")) {
                val id = o.getStringOr("id", "")
                if (id.isEmpty()) continue
                outputs += id to o.getLongOr("ct", 0L)
            }
            val targets = ArrayList<Pair<BlockPos, net.minecraft.core.Direction>>()
            for (t in c.childrenListOrEmpty("targets")) {
                val p = t.getLongOr("p", 0L)
                val f = t.getIntOr("f", 0)
                val faces = net.minecraft.core.Direction.entries
                if (f !in faces.indices) continue
                targets += BlockPos.of(p) to faces[f]
            }
            opResumeInfo[opId] = OpResumeInfo(api, outputs, targets)
        }
        // Defensive cleanup: opResumeInfo entries reference op IDs that only mean anything
        // within the loaded scheduler plan. If no plan (or different ops), drop them.
        val planOpIds = scheduler.currentPlan?.ops?.map { it.id }?.toSet().orEmpty()
        if (opResumeInfo.keys.any { it !in planOpIds }) {
            opResumeInfo.keys.retainAll(planOpIds)
        }
    }

    override fun getUpdateTag(registries: HolderLookup.Provider): CompoundTag {
        val tag = saveWithoutMetadata(registries)
        // Strip server-only pending job metadata from client sync.
        tag.remove("originalCraftId")
        tag.remove("originalCraftCount")
        tag.remove("pendingCount")
        tag.remove("pendingOutputs")
        tag.remove("pendingPullTargets")
        tag.remove("scheduler")
        return tag
    }

    override fun getUpdatePacket(): Packet<ClientGamePacketListener> {
        return ClientboundBlockEntityDataPacket.create(this)
    }
}
